/**
 * Demo catalogue for Dhiya's Pharmousy.
 *
 * Compliance note: `pharmacistNote` is the only place usage guidance appears.
 * It is stored as plain text entered by a pharmacist and is never generated,
 * inferred or templated by this codebase.
 *
 * Prices and MRPs are illustrative sample data, not real commercial terms.
 */

export const categories = [
  { slug: 'pharmacy-products', name: 'Pharmacy Products', tagline: 'Prescription & OTC medicines', icon: 'pill', accent: 'primary', sort_order: 1 },
  { slug: 'baby-care', name: 'Baby Care', tagline: 'Diapers, infant nutrition & care', icon: 'motherBaby', accent: 'rose', sort_order: 2 },
  { slug: 'nutritional-drinks', name: 'Nutritional Drinks & Supplements', tagline: 'Protein, vitamins & tonics', icon: 'nutrition', accent: 'gold', sort_order: 3 },
  { slug: 'women-care', name: 'Women Care', tagline: 'Hygiene, health & wellness', icon: 'heart', accent: 'rose', sort_order: 4 },
  { slug: 'personal-care', name: 'Personal Care', tagline: 'Bath, hair, oral & skin care', icon: 'soap', accent: 'sky', sort_order: 5 },
  { slug: 'ayurveda', name: 'Ayurveda', tagline: 'Classical herbal preparations', icon: 'leaf', accent: 'primary', sort_order: 6 },
  { slug: 'health-devices', name: 'Health Devices', tagline: 'Monitors, thermometers & oximeters', icon: 'device', accent: 'lilac', sort_order: 7 },
  { slug: 'home-essentials', name: 'Home Essentials', tagline: 'Everyday household health', icon: 'home', accent: 'cream', sort_order: 8 },
  { slug: 'health-condition', name: 'Health Condition', tagline: 'Condition-wise shopping', icon: 'stethoscope', accent: 'primary', sort_order: 9 },
];

export const brands = [
  { slug: 'dhiyas-pharmousy', name: "Dhiya's Pharmousy", monogram: 'DP', accent: 'gold', sort_order: 1 },
  { slug: 'apollo', name: 'Apollo', monogram: 'AP', accent: 'primary', sort_order: 2 },
  { slug: 'dabur', name: 'Dabur', monogram: 'DB', accent: 'gold', sort_order: 3 },
  { slug: 'himalaya', name: 'Himalaya', monogram: 'HL', accent: 'primary', sort_order: 4 },
  { slug: 'gsk', name: 'GSK', monogram: 'GS', accent: 'sky', sort_order: 5 },
  { slug: 'pfizer', name: 'Pfizer', monogram: 'PF', accent: 'lilac', sort_order: 6 },
  { slug: 'cipla', name: 'Cipla', monogram: 'CP', accent: 'sky', sort_order: 7 },
  { slug: 'mamaearth', name: 'Mamaearth', monogram: 'ME', accent: 'rose', sort_order: 8 },
  { slug: 'johnson-and-johnson', name: 'Johnson & Johnson', monogram: 'JJ', accent: 'rose', sort_order: 9 },
  { slug: 'bausch-and-lomb', name: 'Bausch + Lomb', monogram: 'BL', accent: 'sky', sort_order: 10 },
  { slug: 'nestle', name: 'Nestle Health Science', monogram: 'NH', accent: 'gold', sort_order: 11 },
  { slug: 'patanjali', name: 'Patanjali', monogram: 'PT', accent: 'primary', sort_order: 12 },
  { slug: 'omron', name: 'Omron', monogram: 'OM', accent: 'lilac', sort_order: 13 },
  { slug: 'royal-stag', name: 'Royal Stag', monogram: 'RS', accent: 'cream', sort_order: 14 },
];

export const conditions = [
  { slug: 'diabetes-care', name: 'Diabetes Care', icon: 'sugar', accent: 'primary', sort_order: 1 },
  { slug: 'cardiac-care', name: 'Cardiac Care', icon: 'heart', accent: 'rose', sort_order: 2 },
  { slug: 'stomach-care', name: 'Stomach Care', icon: 'gut', accent: 'gold', sort_order: 3 },
  { slug: 'pain-relief', name: 'Pain Relief', icon: 'bandage', accent: 'cream', sort_order: 4 },
  { slug: 'liver-care', name: 'Liver Care', icon: 'shield', accent: 'primary', sort_order: 5 },
  { slug: 'oral-care', name: 'Oral Care', icon: 'tooth', accent: 'sky', sort_order: 6 },
  { slug: 'respiratory', name: 'Respiratory', icon: 'inhaler', accent: 'lilac', sort_order: 7 },
  { slug: 'sexual-health', name: 'Sexual Health', icon: 'shield', accent: 'rose', sort_order: 8 },
  { slug: 'elderly-care', name: 'Elderly Care', icon: 'senior', accent: 'cream', sort_order: 9 },
  { slug: 'cold-immunity', name: 'Cold & Immunity', icon: 'shield', accent: 'primary', sort_order: 10 },
];

/** accent values are limited to the palettes defined in artwork.js */
export const products = [
  // ---------------------------------------------------------- pharmacy (Rx)
  {
    slug: 'amoxycillin-500mg-capsules-10s',
    sku: 'DP-AMX-500',
    name: 'Amoxycillin 500mg Capsules',
    brand: 'Cipla',
    category: 'pharmacy-products',
    condition: null,
    salt: 'Amoxycillin 500mg',
    description:
      'A broad-spectrum antibiotic capsules dispensed against a valid prescription. Each strip contains 10 capsules.',
    pharmacistNote:
      'Dispense only against a valid prescription. Store in a cool, dry place below 25°C, protected from moisture.',
    price: 62, mrp: 78, rx: true, schedule: 'Schedule H',
    stock: 48, unit: '10 Capsules', pack: 'Strip of 10', icon: 'capsule', accent: 'primary', featured: true,
  },
  {
    slug: 'azithromycin-500mg-tablets-3s',
    sku: 'DP-AZI-500',
    name: 'Azithromycin 500mg Tablets',
    brand: 'Apollo',
    category: 'pharmacy-products',
    condition: 'respiratory',
    salt: 'Azithromycin 500mg',
    description: 'Antibiotic tablets supplied in a strip of 3, dispensed against a valid prescription.',
    pharmacistNote:
      'Prescription-only medicine. Keep out of reach of children. Store below 25°C in a dry place.',
    price: 118, mrp: 134, rx: true, schedule: 'Schedule H',
    stock: 30, unit: '3 Tablets', pack: 'Strip of 3', icon: 'tablet', accent: 'sky', featured: true,
  },
  {
    slug: 'metformin-500mg-tablets-10s',
    sku: 'DP-MET-500',
    name: 'Metformin 500mg Tablets',
    brand: 'Cipla',
    category: 'health-condition',
    condition: 'diabetes-care',
    salt: 'Metformin Hydrochloride 500mg',
    description: 'Oral anti-diabetic tablets supplied in a strip of 10 against a valid prescription.',
    pharmacistNote:
      'Prescription-only medicine dispensed as per the prescribing doctor. Store below 30°C, protected from sunlight.',
    price: 34, mrp: 42, rx: true, schedule: 'Schedule H',
    stock: 90, unit: '10 Tablets', pack: 'Strip of 10', icon: 'tablet', accent: 'primary', featured: false,
  },
  {
    slug: 'atorvastatin-10mg-tablets-10s',
    sku: 'DP-ATV-010',
    name: 'Atorvastatin 10mg Tablets',
    brand: 'Pfizer',
    category: 'health-condition',
    condition: 'cardiac-care',
    salt: 'Atorvastatin Calcium 10mg',
    description: 'Statin tablets supplied in a strip of 10, dispensed against a valid prescription.',
    pharmacistNote:
      'Prescription-only medicine. Store in a cool, dry place below 30°C, protected from light.',
    price: 56, mrp: 70, rx: true, schedule: 'Schedule H',
    stock: 64, unit: '10 Tablets', pack: 'Strip of 10', icon: 'tablet', accent: 'lilac', featured: false,
  },
  {
    slug: 'pantoprazole-40mg-tablets-10s',
    sku: 'DP-PAN-040',
    name: 'Pantoprazole 40mg Tablets',
    brand: 'Cipla',
    category: 'health-condition',
    condition: 'stomach-care',
    salt: 'Pantoprazole Sodium 40mg',
    description: 'Anti-acid tablets supplied in a strip of 10, dispensed against a valid prescription.',
    pharmacistNote:
      'Prescription-only medicine. Take as directed by the prescribing doctor. Store below 25°C.',
    price: 48, mrp: 62, rx: true, schedule: 'Schedule H',
    stock: 72, unit: '10 Tablets', pack: 'Strip of 10', icon: 'tablet', accent: 'gold', featured: false,
  },
  {
    slug: 'paracetamol-650mg-tablets-10s-rx',
    sku: 'DP-PAR-650R',
    name: 'Paracetamol 650mg Tablets (Pack of 15)',
    brand: 'GSK',
    category: 'pharmacy-products',
    condition: 'pain-relief',
    salt: 'Paracetamol 650mg',
    description:
      'Prescription pack of paracetamol 650mg tablets. Prescription required for this pack size.',
    pharmacistNote:
      'Dispense against a valid prescription. Do not exceed the dose advised by the doctor.',
    price: 27, mrp: 33, rx: true, schedule: 'Schedule H',
    stock: 120, unit: '15 Tablets', pack: 'Pack of 15', icon: 'tablet', accent: 'cream', featured: false,
  },
  {
    slug: 'vitamin-d3-capsules-60s',
    sku: 'DP-VD3-060',
    name: 'Vitamin D3 60,000 IU Capsules',
    brand: "Dhiya's Pharmousy",
    category: 'nutritional-drinks',
    condition: 'elderly-care',
    salt: 'Cholecalciferol 60000 IU',
    description:
      'High-strength vitamin D3 capsules supplied in a pack of 4, dispensed against a valid prescription.',
    pharmacistNote:
      'Prescription-only. The dose and frequency must follow the prescribing doctor’s instruction. Take with a meal containing fat.',
    price: 148, mrp: 185, rx: true, schedule: 'Schedule H',
    stock: 40, unit: '4 Capsules', pack: 'Pack of 4', icon: 'capsule', accent: 'gold', featured: true,
  },
  {
    slug: 'thyroxine-50mcg-tablets-10s',
    sku: 'DP-THY-050',
    name: 'Thyroxine 50mcg Tablets',
    brand: 'Pfizer',
    category: 'health-condition',
    condition: null,
    salt: 'Levothyroxine Sodium 50mcg',
    description: 'Thyroid hormone tablets supplied in a strip of 10 against a valid prescription.',
    pharmacistNote:
      'Prescription-only. Dispense exactly as per the prescription. Store below 25°C, protected from light.',
    price: 92, mrp: 110, rx: true, schedule: 'Schedule H1',
    stock: 26, unit: '10 Tablets', pack: 'Strip of 10', icon: 'tablet', accent: 'sky', featured: false,
  },
  {
    slug: 'montelukast-10mg-tablets-10s',
    sku: 'DP-MON-010',
    name: 'Montelukast 10mg Tablets',
    brand: 'GSK',
    category: 'health-condition',
    condition: 'respiratory',
    salt: 'Montelukast Sodium 10mg',
    description: 'Leukotriene receptor antagonist tablets, supplied against a valid prescription.',
    pharmacistNote:
      'Prescription-only medicine. Take in the evening or as directed by the doctor. Not for children under 6 months.',
    price: 164, mrp: 198, rx: true, schedule: 'Schedule H',
    stock: 22, unit: '10 Tablets', pack: 'Strip of 10', icon: 'tablet', accent: 'sky', featured: false,
  },
  {
    slug: 'sildenafil-50mg-tablets-4s',
    sku: 'DP-SIL-050',
    name: 'Sildenafil 50mg Tablets',
    brand: 'Pfizer',
    category: 'pharmacy-products',
    condition: 'sexual-health',
    salt: 'Sildenafil Citrate 50mg',
    description: 'Dispensed strictly against a valid prescription, as required by the drug regulator.',
    pharmacistNote:
      'Schedule H1 medicine. Valid prescription mandatory. Sold only to male patients above 18 years. Pharmacist will contact you to confirm age and prescription.',
    price: 385, mrp: 450, rx: true, schedule: 'Schedule H1',
    stock: 18, unit: '4 Tablets', pack: 'Pack of 4', icon: 'tablet', accent: 'rose', featured: false,
  },

  // ------------------------------------------------------------ pharmacy (OTC)
  {
    slug: 'paracetamol-650mg-tablets-10s',
    sku: 'DP-PAR-650',
    name: 'Paracetamol 650mg Tablets',
    brand: "Dhiya's Pharmousy",
    category: 'pharmacy-products',
    condition: 'pain-relief',
    salt: 'Paracetamol 650mg',
    description: 'Over-the-counter analgesic and antipyretic tablets. No prescription required.',
    pharmacistNote:
      'Do not take more than 2 tablets in 24 hours unless advised otherwise. Consult our pharmacist if you have liver disease or take other medicines.',
    price: 19, mrp: 26, rx: false, schedule: null,
    stock: 220, unit: '10 Tablets', pack: 'Strip of 10', icon: 'tablet', accent: 'primary', featured: true,
  },
  {
    slug: 'cough-syrup-100ml',
    sku: 'DP-CSH-100',
    name: 'Cough Syrup 100ml',
    brand: 'Himalaya',
    category: 'pharmacy-products',
    condition: 'respiratory',
    salt: 'Herbal cough syrup',
    description: 'Sugar-free herbal cough syrup for adults and children above 5 years. Over-the-counter.',
    pharmacistNote:
      'Shake well before use. Store in a cool place after opening. Use within 30 days of opening.',
    price: 96, mrp: 120, rx: false, schedule: null,
    stock: 85, unit: '100 ml', pack: 'Bottle', icon: 'syrupBottle', accent: 'primary', featured: true,
  },
  {
    slug: 'ursodeoxycholic-acid-300mg-10s',
    sku: 'DP-UDC-300',
    name: 'Ursodeoxycholic Acid 300mg Tablets',
    brand: 'Cipla',
    category: 'health-condition',
    condition: 'liver-care',
    salt: 'Ursodeoxycholic Acid 300mg',
    description: 'Bile-acid tablets supplied in a strip of 10 against a valid prescription.',
    pharmacistNote:
      'Prescription-only medicine. Take as directed by the prescribing doctor. Store below 30°C, protected from moisture.',
    price: 176, mrp: 205, rx: true, schedule: 'Schedule H',
    stock: 34, unit: '10 Tablets', pack: 'Strip of 10', icon: 'tablet', accent: 'primary', featured: false,
  },
  {
    slug: 'syrup-electral-200ml',
    sku: 'DP-ELD-200',
    name: 'Oral Rehydration Solution 200ml',
    brand: "Dhiya's Pharmousy",
    category: 'pharmacy-products',
    condition: 'stomach-care',
    salt: 'Oral Rehydration Salts',
    description: 'Ready-to-drink oral rehydration fluid to replace salts and water lost through dehydration.',
    pharmacistNote: 'Drink in small sips as needed. Once opened, consume within 24 hours.',
    price: 22, mrp: 28, rx: false, schedule: null,
    stock: 260, unit: '200 ml', pack: 'Bottle', icon: 'bottle', accent: 'sky', featured: false,
  },
  {
    slug: 'cetirizine-10mg-tablets-10s',
    sku: 'DP-CET-010',
    name: 'Cetirizine 10mg Tablets',
    brand: 'Cipla',
    category: 'pharmacy-products',
    condition: 'cold-immunity',
    salt: 'Cetirizine Hydrochloride 10mg',
    description: 'Anti-allergy tablets for relief of sneezing, runny nose and itchy eyes. Over-the-counter.',
    pharmacistNote:
      'May cause drowsiness. Avoid driving if you feel sleepy after taking it. Consult our pharmacist before use in pregnancy.',
    price: 12, mrp: 18, rx: false, schedule: null,
    stock: 310, unit: '10 Tablets', pack: 'Strip of 10', icon: 'tablet', accent: 'sky', featured: false,
  },
  {
    slug: 'loratadine-10mg-tablets-10s',
    sku: 'DP-LOR-010',
    name: 'Loratadine 10mg Tablets',
    brand: 'GSK',
    category: 'pharmacy-products',
    condition: 'cold-immunity',
    salt: 'Loratadine 10mg',
    description: 'Non-drowsy anti-allergy tablets for daily use. Over-the-counter.',
    pharmacistNote:
      'Once-daily tablet. Consult our pharmacist if symptoms persist beyond five days.',
    price: 15, mrp: 21, rx: false, schedule: null,
    stock: 260, unit: '10 Tablets', pack: 'Strip of 10', icon: 'tablet', accent: 'sky', featured: false,
  },
  {
    slug: 'ors-electral-powder-sachet',
    sku: 'DP-ORS-001',
    name: 'ORS Electrolyte Powder',
    brand: "Dhiya's Pharmousy",
    category: 'pharmacy-products',
    condition: 'stomach-care',
    salt: 'Oral Rehydration Salts',
    description: 'WHO-formula oral rehydration salts for mild to moderate dehydration. Over-the-counter.',
    pharmacistNote:
      'Dissolve one sachet in exactly 1 litre of clean water. Use within 24 hours of preparation. Do not sweeten.',
    price: 10, mrp: 15, rx: false, schedule: null,
    stock: 400, unit: '4.2 g', pack: 'Sachet', icon: 'powder', accent: 'gold', featured: false,
  },
  {
    slug: 'betadine-gargle-200ml',
    sku: 'DP-BTD-200',
    name: 'Betadine Gargle & Mouthwash',
    brand: 'Johnson & Johnson',
    category: 'personal-care',
    condition: 'oral-care',
    salt: 'Povidone Iodine 2%',
    description: 'Povidone iodine gargle for sore throat and oral hygiene. Over-the-counter.',
    pharmacistNote:
      'Dilute as directed on the label. Do not swallow. Avoid use if you are allergic to iodine.',
    price: 128, mrp: 149, rx: false, schedule: null,
    stock: 74, unit: '200 ml', pack: 'Bottle', icon: 'bottle', accent: 'sky', featured: true,
  },
  {
    slug: 'first-aid-bandage-roll',
    sku: 'DP-FAB-01',
    name: 'First Aid Bandage Roll',
    brand: "Dhiya's Pharmousy",
    category: 'home-essentials',
    condition: null,
    salt: 'Cotton crepe bandage',
    description: 'Sterile elastic crepe bandage for sprains, strains and dressing support.',
    pharmacistNote: 'Keep clean and dry. Do not apply over an open wound without a sterile pad.',
    price: 68, mrp: 85, rx: false, schedule: null,
    stock: 140, unit: '4 in', pack: '4 in x 4 in', icon: 'bandage', accent: 'cream', featured: false,
  },

  // ------------------------------------------------------------- personal care
  {
    slug: 'herbal-shampoo-340ml',
    sku: 'DP-HSP-340',
    name: 'Herbal Anti-Dandruff Shampoo',
    brand: 'Dabur',
    category: 'personal-care',
    condition: null,
    salt: 'Herbal shampoo',
    description: 'Ayurvedic anti-dandruff shampoo with neem and amla for gentle daily use.',
    pharmacistNote: 'For external use only. Rinse well. Discontinue if irritation occurs.',
    price: 218, mrp: 265, rx: false, schedule: null,
    stock: 58, unit: '340 ml', pack: 'Bottle', icon: 'bottle', accent: 'primary', featured: true,
  },
  {
    slug: 'neem-face-wash-100g',
    sku: 'DP-NFW-100',
    name: 'Neem Face Wash',
    brand: 'Dabur',
    category: 'personal-care',
    condition: null,
    salt: 'Neem extract',
    description: 'Oil-control face wash for normal to oily skin. Soap-free and paraben-free.',
    pharmacistNote: 'For external use only. Avoid direct contact with eyes.',
    price: 89, mrp: 110, rx: false, schedule: null,
    stock: 96, unit: '100 g', pack: 'Tube', icon: 'cream', accent: 'primary', featured: false,
  },
  {
    slug: 'toothpaste-oral-b-150g',
    sku: 'DP-TPP-150',
    name: 'Oral-B Complete Toothpaste',
    brand: 'Johnson & Johnson',
    category: 'personal-care',
    condition: 'oral-care',
    salt: 'Fluoride toothpaste 1450ppm',
    description: 'Complete care toothpaste with cavity protection and fresh breath. Over-the-counter.',
    pharmacistNote: 'For children under 6, use a pea-sized amount and supervise brushing.',
    price: 132, mrp: 160, rx: false, schedule: null,
    stock: 120, unit: '150 g', pack: 'Tube', icon: 'cream', accent: 'sky', featured: false,
  },
  {
    slug: 'bath-soap-pack-of-4',
    sku: 'DP-BSP-004',
    name: 'Moisturising Bath Soap',
    brand: 'Dabur',
    category: 'personal-care',
    condition: null,
    salt: 'Herbal soap',
    description: 'Pack of 4 bathing bars enriched with glycerin and aloe vera.',
    pharmacistNote: 'For external use only. Discontinue if irritation occurs.',
    price: 178, mrp: 228, rx: false, schedule: null,
    stock: 64, unit: '4 x 100 g', pack: 'Pack of 4', icon: 'soap', accent: 'rose', featured: false,
  },
  {
    slug: 'sanitary-napkins-regular-pack-10',
    sku: 'DP-SNP-010',
    name: 'Sanitary Napkins Regular',
    brand: 'Dhiya\'s Pharmousy',
    category: 'women-care',
    condition: null,
    salt: 'Regular absorbency',
    description: 'Regular absorbency sanitary napkins with leak-lock protection. Pack of 10.',
    pharmacistNote: 'Change every 4-6 hours. Wash hands before and after use.',
    price: 64, mrp: 79, rx: false, schedule: null,
    stock: 200, unit: '10 pads', pack: 'Pack of 10', icon: 'powder', accent: 'rose', featured: false,
  },
  {
    slug: 'intimate-wash-200ml',
    sku: 'DP-IWS-200',
    name: 'Intimate Wash pH Balanced',
    brand: 'Dhiya\'s Pharmousy',
    category: 'women-care',
    condition: null,
    salt: 'pH balanced wash',
    description: 'Gentle pH-balanced intimate wash for daily use.',
    pharmacistNote: 'External use only. Discontinue if irritation occurs and consult our pharmacist.',
    price: 145, mrp: 180, rx: false, schedule: null,
    stock: 88, unit: '200 ml', pack: 'Bottle', icon: 'bottle', accent: 'lilac', featured: false,
  },

  // -------------------------------------------------------------- baby care
  {
    slug: 'baby-diaper-medium-pack-30',
    sku: 'DP-BDM-030',
    name: 'Baby Diapers Medium',
    brand: 'Mamaearth',
    category: 'baby-care',
    condition: null,
    salt: 'Ultra dry diaper',
    description: 'Ultra-dry taped diapers for medium size babies. Pack of 30.',
    pharmacistNote: 'Keep away from the reach of children after use. Dispose responsibly.',
    price: 449, mrp: 549, rx: false, schedule: null,
    stock: 36, unit: '30 diapers', pack: 'Pack of 30', icon: 'powder', accent: 'rose', featured: true,
  },
  {
    slug: 'infant-formula-stage-1-200g',
    sku: 'DP-IFM-200',
    name: 'Infant Formula Stage 1',
    brand: 'Nestle Health Science',
    category: 'baby-care',
    condition: null,
    salt: 'Infant formula',
    description: 'Stage 1 infant formula suitable from birth, for infants who are not breastfed.',
    pharmacistNote:
      'Use exactly as directed on the pack. Prepare each feed freshly. Do not use reconstituted formula after one hour.',
    price: 585, mrp: 660, rx: false, schedule: null,
    stock: 28, unit: '200 g', pack: 'Tin', icon: 'bottle', accent: 'gold', featured: false,
  },
  {
    slug: 'baby-massage-oil-200ml',
    sku: 'DP-BMO-200',
    name: 'Baby Massage Oil',
    brand: 'Johnson & Johnson',
    category: 'baby-care',
    condition: null,
    salt: 'Baby massage oil',
    description: 'Lightweight massage oil formulated for a newborn’s delicate skin.',
    pharmacistNote: 'External use only. Patch test before first use. For use above 3 months.',
    price: 178, mrp: 215, rx: false, schedule: null,
    stock: 62, unit: '200 ml', pack: 'Bottle', icon: 'oil', accent: 'gold', featured: false,
  },
  {
    slug: 'baby-soap-gentle-200ml',
    sku: 'DP-BSG-200',
    name: 'Gentle Baby Bath Soap',
    brand: 'Mamaearth',
    category: 'baby-care',
    condition: null,
    salt: 'Tear-free baby soap',
    description: 'Tear-free, hypoallergenic body wash for newborns and infants.',
    pharmacistNote: 'External use only. Keep out of reach of children.',
    price: 199, mrp: 249, rx: false, schedule: null,
    stock: 54, unit: '200 ml', pack: 'Bottle', icon: 'soap', accent: 'rose', featured: false,
  },

  // ------------------------------------------------------ nutrition & devices
  {
    slug: 'protein-supplement-vanilla-1kg',
    sku: 'DP-PRT-1KG',
    name: 'Whey Protein Supplement',
    brand: 'Dhiya\'s Pharmousy',
    category: 'nutritional-drinks',
    condition: null,
    salt: 'Whey protein concentrate',
    description: 'Vanilla-flavoured protein supplement powder for daily nutrition support.',
    pharmacistNote:
      'Food supplement, not a medicine. Consult a doctor if you have a chronic medical condition, are pregnant, or are on medication.',
    price: 1120, mrp: 1450, rx: false, schedule: null,
    stock: 22, unit: '1 kg', pack: 'Tub', icon: 'bottle', accent: 'gold', featured: true,
  },
  {
    slug: 'multivitamin-tablets-30s',
    sku: 'DP-MVT-030',
    name: 'Daily Multivitamin Tablets',
    brand: 'Dhiya\'s Pharmousy',
    category: 'nutritional-drinks',
    condition: 'elderly-care',
    salt: 'Multivitamin & multimineral',
    description: 'Daily multivitamin and multimineral supplement for adults. Over-the-counter.',
    pharmacistNote:
      'Dietary supplement, not a medicine. Do not exceed one tablet per day.',
    price: 249, mrp: 320, rx: false, schedule: null,
    stock: 78, unit: '30 Tablets', pack: 'Bottle of 30', icon: 'tablet', accent: 'gold', featured: false,
  },
  {
    slug: 'bp-monitor-automatic',
    sku: 'DP-BPM-001',
    name: 'Automatic Blood Pressure Monitor',
    brand: 'Omron',
    category: 'health-devices',
    condition: 'cardiac-care',
    salt: 'Automatic BP monitor',
    description: 'Clinically validated upper-arm automatic blood pressure monitor with irregular heartbeat detection.',
    pharmacistNote:
      'Rest seated for five minutes before measuring. Use the cuff on a bare arm at heart level. This is a device, not a diagnosis.',
    price: 2280, mrp: 2799, rx: false, schedule: null,
    stock: 14, unit: '1 unit', pack: 'Box', icon: 'device', accent: 'lilac', featured: true,
  },
  {
    slug: 'digital-thermometer',
    sku: 'DP-THM-001',
    name: 'Digital Thermometer',
    brand: "Dhiya's Pharmousy",
    category: 'health-devices',
    condition: 'cold-immunity',
    salt: 'Digital thermometer',
    description: 'Fast-read digital thermometer with fever alarm and memory of the last reading.',
    pharmacistNote: 'For external and rectal use. Wash the tip before and after each use.',
    price: 168, mrp: 220, rx: false, schedule: null,
    stock: 92, unit: '1 unit', pack: 'Box', icon: 'thermometer', accent: 'sky', featured: false,
  },
  {
    slug: 'pulse-oximeter-fingertip',
    sku: 'DP-OXI-001',
    name: 'Fingertip Pulse Oximeter',
    brand: "Dhiya's Pharmousy",
    category: 'health-devices',
    condition: 'respiratory',
    salt: 'Pulse oximeter',
    description: 'Fingertip pulse oximeter displaying SpO₂, pulse rate and perfusion index.',
    pharmacistNote:
      'Warm your hand before reading and keep still for 30 seconds. Wash the sensor before and after each use.',
    price: 749, mrp: 999, rx: false, schedule: null,
    stock: 26, unit: '1 unit', pack: 'Box', icon: 'device', accent: 'sky', featured: false,
  },
  {
    slug: 'nebulizer-compressor',
    sku: 'DP-NEB-001',
    name: 'Nebulizer Compressor',
    brand: 'Omron',
    category: 'health-devices',
    condition: 'respiratory',
    salt: 'Air compressor nebulizer',
    description: 'Quiet air-compressor nebulizer for home nebulisation, suitable for adults and children.',
    pharmacistNote:
      'Use only the medicines prescribed by your doctor. Clean the nebulizer chamber after every use. This is a device and not a medicine.',
    price: 2150, mrp: 2650, rx: false, schedule: null,
    stock: 11, unit: '1 unit', pack: 'Box', icon: 'inhaler', accent: 'lilac', featured: false,
  },
  {
    slug: 'himalaya-neem-face-pack',
    sku: 'DP-HNF-100',
    name: 'Neem & Tulsi Face Pack',
    brand: 'Himalaya',
    category: 'ayurveda',
    condition: null,
    salt: 'Herbal face pack',
    description: 'Clay-based herbal face pack with neem and tulsi for weekly use.',
    pharmacistNote: 'For external use only. Avoid the eye area.',
    price: 145, mrp: 185, rx: false, schedule: null,
    stock: 68, unit: '100 g', pack: 'Tube', icon: 'leaf', accent: 'primary', featured: false,
  },
  {
    slug: 'patanjali-ajwain-cough-drops',
    sku: 'DP-AJW-050',
    name: 'Ajwain Cough Drops',
    brand: 'Patanjali',
    category: 'ayurveda',
    condition: 'respiratory',
    salt: 'Ajwain, candy',
    description: 'Sugar-free herbal cough drops with ajwain. Over-the-counter.',
    pharmacistNote: 'For external oral use. Do not exceed eight drops per day. Not for children below 4 years.',
    price: 32, mrp: 45, rx: false, schedule: null,
    stock: 210, unit: '50 drops', pack: 'Bottle', icon: 'drops', accent: 'primary', featured: false,
  },
  {
    slug: 'triphala-churna-200g',
    sku: 'DP-TRP-200',
    name: 'Triphala Churna',
    brand: 'Patanjali',
    category: 'ayurveda',
    condition: 'stomach-care',
    salt: 'Triphala churna',
    description: 'Classical Ayurvedic herbal powder. Over-the-counter preparation.',
    pharmacistNote:
      'Consult our pharmacist before use if you are pregnant, breastfeeding, or on long-term medication.',
    price: 96, mrp: 125, rx: false, schedule: null,
    stock: 84, unit: '200 g', pack: 'Pouch', icon: 'powder', accent: 'primary', featured: false,
  },
  {
    slug: 'amla-hair-oil-200ml',
    sku: 'DP-AHL-200',
    name: 'Amla Hair Oil',
    brand: 'Dabur',
    category: 'ayurveda',
    condition: null,
    salt: 'Amla based hair oil',
    description: 'Amla-infused hair oil for scalp nourishment and reduced hair fall.',
    pharmacistNote: 'For external use only. Patch test if you have a sensitive scalp.',
    price: 158, mrp: 199, rx: false, schedule: null,
    stock: 72, unit: '200 ml', pack: 'Bottle', icon: 'oil', accent: 'primary', featured: false,
  },
  {
    slug: 'royal-stag-premium-razor-blades-8s',
    sku: 'DP-RSR-008',
    name: 'Premium Safety Razor Blades',
    brand: 'Royal Stag',
    category: 'personal-care',
    condition: null,
    salt: 'Safety razor blades',
    description: 'Pack of 8 stainless steel double-edge safety razor blades for a close shave.',
    pharmacistNote: 'Handle with care. Keep out of reach of children. Dispose in a sharps container.',
    price: 120, mrp: 150, rx: false, schedule: null,
    stock: 130, unit: '8 blades', pack: 'Pack of 8', icon: 'comb', accent: 'cream', featured: false,
  },
  {
    slug: 'n95-face-masks-50s',
    sku: 'DP-N95-050',
    name: 'N95 Face Masks',
    brand: "Dhiya's Pharmousy",
    category: 'home-essentials',
    condition: 'respiratory',
    salt: 'N95 respirator',
    description: 'Box of 50 foldable N95 respirator masks with adjustable nose clip and ear loops.',
    pharmacistNote: 'For single use. Do not reuse. Check the seal around the nose each time.',
    price: 450, mrp: 550, rx: false, schedule: null,
    stock: 48, unit: '50 masks', pack: 'Box of 50', icon: 'mask', accent: 'sky', featured: false,
  },
  {
    slug: 'hand-sanitizer-500ml',
    sku: 'DP-HND-500',
    name: 'Hand Sanitizer 70% Alcohol',
    brand: "Dhiya's Pharmousy",
    category: 'home-essentials',
    condition: 'cold-immunity',
    salt: '70% isopropyl alcohol',
    description: 'Antibacterial hand sanitizer with moisturiser. Suitable for pocket and trolley use.',
    pharmacistNote:
      'For external use only. Keep away from flame. Do not apply to broken skin or near the eyes.',
    price: 138, mrp: 175, rx: false, schedule: null,
    stock: 105, unit: '500 ml', pack: 'Bottle', icon: 'drops', accent: 'primary', featured: false,
  },
  {
    slug: 'bausch-lomb-saline-10ml',
    sku: 'DP-SLV-010',
    name: 'Saline Eye Drops',
    brand: 'Bausch + Lomb',
    category: 'personal-care',
    condition: null,
    salt: 'Sodium chloride 0.9%',
    description: 'Sterile isotonic saline eye drops for eye comfort and lens rinsing. Over-the-counter.',
    pharmacistNote:
      'Do not touch the dropper tip to the eye. Use before opening a new contact lens. Discard 30 days after opening.',
    price: 125, mrp: 155, rx: false, schedule: null,
    stock: 88, unit: '10 ml', pack: 'Bottle', icon: 'drops', accent: 'sky', featured: false,
  },
];

export const coupons = [
  { code: 'WELCOME10', description: '10% off on your first order above ₹299', kind: 'percent', value: 10, min_order: 299, max_discount: 120, applies_to_rx: false, is_active: true },
  { code: 'THISUUR50', description: 'Flat ₹50 off above ₹599', kind: 'flat', value: 50, min_order: 599, max_discount: 50, applies_to_rx: false, is_active: true },
  { code: 'DHOLASE20', description: '20% off up to ₹200 on wellness products', kind: 'percent', value: 20, min_order: 700, max_discount: 200, applies_to_rx: false, is_active: true },
];

export const banners = [
  {
    badge: 'JUST LAUNCHED',
    title: 'Home Delivery Across Ollur',
    subtitle: 'Order before 8 PM and we will deliver the same evening. Free above ₹499.',
    cta_label: 'Order Now',
    cta_href: '/catalog',
    theme: 'primary',
    placement: 'home_promo',
    sort_order: 1,
    is_active: true,
  },
  {
    badge: 'NEW',
    title: 'Pharmacist On Call',
    subtitle: 'Talk to our in-store pharmacist free of cost on WhatsApp at 9142225559.',
    cta_label: 'Chat on WhatsApp',
    cta_href: 'https://wa.me/919142225559',
    theme: 'gold',
    placement: 'home_promo',
    sort_order: 2,
    is_active: true,
  },
  {
    badge: 'VALUE DEALS',
    title: 'Everyday Essentials Under ₹100',
    subtitle: 'Trusted brands for fever, cough, allergies and daily hygiene at fair prices.',
    cta_label: 'Browse Deals',
    cta_href: '/catalog?maxPrice=100',
    theme: 'dark',
    placement: 'home_promo',
    sort_order: 3,
    is_active: true,
  },
];
